name: Binance

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Binance tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v4
  
      - run: python3 binance/pairs.py -m -q BTC
      - run: python3 binance/pairs.py -m -q USDT
      - run: python3 binance/pairs.py -m -q ETH
      - run: python3 binance/pairs.py -m -q BNB
      - run: python3 binance/pairs.py -m
      - run: python3 binance/pairs.py -q BTC
      - run: python3 binance/pairs.py -q USDT
      - run: python3 binance/pairs.py -q ETH
      - run: python3 binance/pairs.py -q BNB
      - run: python3 binance/pairs.py
      - run: python3 binance/pairs.py -f

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add binance/
          git diff-index --quiet HEAD || git commit -m "Binance: automatic update" -a
          git pull --rebase && git push
